{"name": "test_update_users[NoValid- Book not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid book_id from Excel: 'None'", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000002D183488B50>, data = {'action': 'update_by_id', 'author': 'Nobody', 'book_id': 0.0, 'expected': False, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_resource.py:45: IndexError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_resource.TestusersAPI object at 0x000002D183488B50>, data = {'action': 'update_by_id', 'author': 'Nobody', 'book_id': 0.0, 'expected': False, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid book_id from Excel: '{data.get('book_id')}'\")\nE           Failed: [ERROR] Invalid book_id from Excel: 'None'\n\ntests\\test_api_resource.py:47: Failed"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "e8182033-633b-4a0c-b74f-17518f343af9-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "552febd9-f712-41e1-aaa6-3f9f05b2ea7b-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "099076b1-5651-4585-a6c0-d1b18d812bce-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'book_id': 0.0, 'author': 'Nobody', 'is_borrowed': 0.0, 'title': 'Ghost Book', 'user': '', 'expected': False, 'note': 'NoValid- Book not found'}"}], "start": 1753271785070, "stop": 1753271785071, "uuid": "5a6cffe1-cd19-4162-b9e1-e976b8b82b9b", "historyId": "829b53ed9a6f6fed97fcf763401943e3", "testCaseId": "8f30c748a08cbeff2e9210952ed78284", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "14888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}