{"name": "test_update_users[NO Valid- ID NOT FOUND]", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000002361826A8B0>, data = {'action': 'update_by_id', 'email': 'YOSSI2@GMAIL.COM', 'expected': False, 'gender': 'male', ...}\n\n        @allure.description(\"Updates users details by users ID.\")\n        @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n        def test_update_users(self, data):\n            expected = parse_bool(data.get(\"expected\"))\n    #◊û◊ï◊¶◊ô◊ê◊î ◊ê◊™ ◊î÷æid ◊û◊î◊û◊ô◊ú◊ï◊ü data, ◊ï◊ê◊ù ◊î◊ï◊ê ◊ú◊ê ◊ß◊ô◊ô◊ù ◊ê◊ï ◊®◊ô◊ß ‚Äì ◊î◊ô◊ê ◊û◊©◊™◊û◊©◊™ ◊ë◊û◊ñ◊î◊î ◊î◊®◊ê◊©◊ï◊ü ◊©◊†◊©◊û◊® ◊ë◊®◊©◊ô◊û◊™ created_ids ◊©◊ú ◊î◊û◊ó◊ú◊ß◊î ◊ë◊™◊ï◊® ◊¢◊®◊ö ◊ë◊®◊ô◊®◊™ ◊û◊ó◊ì◊ú.\n>           id = extract_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_resource.py:46: IndexError"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "cfc9960f-b316-49d7-9029-ac5ba0b8e5bc-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "9b011ba3-a0f7-41af-9a59-aef45291c6af-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "7c26c4f7-e14b-469d-8514-c406e7ab12e0-attachment.txt", "type": "text/plain"}, {"name": "[None] request", "source": "a072997c-ed28-4eee-8e48-fd376fdffe24-attachment.txt", "type": "text/plain"}, {"name": "Allure Attachment Error", "source": "698db9e0-0456-4722-a9f1-1eadee8af049-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'id': 121212.0, 'name': 'UPDATED_NAME2', 'email': 'YOSSI2@GMAIL.COM', 'gender': 'male', 'status': 'active', 'expected': False, 'note': 'NO Valid- ID NOT FOUND'}"}], "start": 1753358496536, "stop": 1753358496537, "uuid": "de434340-215f-425b-9914-8237878b36c9", "historyId": "f8796b790ab008710fc541bcea9e630e", "testCaseId": "606f5d6c173cdf14acb8881bab7fb526", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "3336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}