{"name": "test_update_post[NoValid - Post not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid id from Excel: '9999.0'", "trace": "self = <tests.test_api_users.TestPostsAPI object at 0x00000246C58D1490>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\nE           AttributeError: type object 'TestPostsAPI' has no attribute 'created_ids'\n\ntests\\test_api_users.py:42: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestPostsAPI object at 0x00000246C58D1490>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid id from Excel: '{data.get('id')}'\")\nE           Failed: [ERROR] Invalid id from Excel: '9999.0'\n\ntests\\test_api_users.py:44: Failed"}, "description": "Updates user details by user ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "7c6dd66a-9fb4-4593-ac73-df20c7dd064e-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "31732ea5-f913-4dbf-93e2-9fc835669b77-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "4d530f64-c18d-4b5a-8183-67f09df6af07-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update', 'id': 9999.0, 'body': 'new', 'id': 'new', 'title': 'HALA', 'expected': False, 'note': 'NoValid - Post not found'}"}], "start": 1753214564260, "stop": 1753214564262, "uuid": "d3f5b580-eeca-48c1-a14b-1111d6e9c7e0", "historyId": "09d24ddfa10f36519b6f86e577346c51", "testCaseId": "16130e9d55726e09524cf02a0fdf9edc", "fullName": "tests.test_api_users.TestPostsAPI#test_update_post", "labels": [{"name": "epic", "value": "posts API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestPostsAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "17968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}