{"name": "test_update_post[NoValid - Post not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid id from Excel: 'None'", "trace": "self = <tests.test_api_users.TestPostsAPI object at 0x0000014937B51370>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\nE           AttributeError: type object 'TestPostsAPI' has no attribute 'created_ids'\n\ntests\\test_api_users.py:41: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestPostsAPI object at 0x0000014937B51370>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid id from Excel: '{data.get('post_id')}'\")\nE           Failed: [ERROR] Invalid id from Excel: 'None'\n\ntests\\test_api_users.py:43: Failed"}, "description": "Updates user details by user ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "eaadb537-3d33-4561-8a28-543f4ab3bcb5-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "ad0109b0-a871-451b-a8df-1a433bdd17cf-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "77756319-abc2-4da0-936a-03e4d756ba51-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update', 'id': 9999.0, 'body': 'new', 'id': 'new', 'title': 1.0, 'expected': False, 'note': 'NoValid - Post not found'}"}], "start": 1753200579356, "stop": 1753200579357, "uuid": "2f1b8e7b-325d-4898-a51b-90a825a1e186", "historyId": "6182ebfc0250cdb8669819fe89c3b6ce", "testCaseId": "16130e9d55726e09524cf02a0fdf9edc", "fullName": "tests.test_api_users.TestPostsAPI#test_update_post", "labels": [{"name": "epic", "value": "posts API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestPostsAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "29096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}