{"name": "test_update_users[Valid-Update Full Data]", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000002A61BA6A9E0>, data = {'action': 'update_by_id', 'email': 'YOSSI@GMAIL.COM', 'expected': True, 'gender': 'male', ...}\n\n        @allure.description(\"Updates users details by users ID.\")\n        @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n        def test_update_users(self, data):\n            expected = parse_bool(data.get(\"expected\"))\n    #◊û◊ï◊¶◊ô◊ê◊î ◊ê◊™ ◊î÷æid ◊û◊î◊û◊ô◊ú◊ï◊ü data, ◊ï◊ê◊ù ◊î◊ï◊ê ◊ú◊ê ◊ß◊ô◊ô◊ù ◊ê◊ï ◊®◊ô◊ß ‚Äì ◊î◊ô◊ê ◊û◊©◊™◊û◊©◊™ ◊ë◊û◊ñ◊î◊î ◊î◊®◊ê◊©◊ï◊ü ◊©◊†◊©◊û◊® ◊ë◊®◊©◊ô◊û◊™ created_ids ◊©◊ú ◊î◊û◊ó◊ú◊ß◊î ◊ë◊™◊ï◊® ◊¢◊®◊ö ◊ë◊®◊ô◊®◊™ ◊û◊ó◊ì◊ú.\n>           id = extract_id(data, fallback_id=self.__class__.created_ids[0])\nE           IndexError: list index out of range\n\ntests\\test_api_resource.py:46: IndexError"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "8d0aa345-b292-459a-9867-cca3195ab650-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "0159ad70-617f-45c8-99e1-2067877ce89f-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "c0512959-f9a5-4b4e-99e2-29b525a19b26-attachment.txt", "type": "text/plain"}, {"name": "[None] request", "source": "eccaa62e-0e44-42ba-95f7-3f922edcaf67-attachment.txt", "type": "text/plain"}, {"name": "Allure Attachment Error", "source": "1a9626d0-4fb4-4541-a9d4-a756ce446549-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'id': '', 'name': 'UPDATED_NAME', 'email': 'YOSSI@GMAIL.COM', 'gender': 'male', 'status': 'active', 'expected': True, 'note': 'Valid-Update Full Data'}"}], "start": 1753358590440, "stop": 1753358590442, "uuid": "43a3c85f-6dc1-4280-a6e0-045561a52fda", "historyId": "0c68cccc2511777797ef9758000ec33b", "testCaseId": "606f5d6c173cdf14acb8881bab7fb526", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "16168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}