{"name": "test_update_post[NoValid - Post not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid id from Excel: 'None'", "trace": "self = <tests.test_api_users.TestPostsAPI object at 0x000001D2FFE01910>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\nE           AttributeError: type object 'TestPostsAPI' has no attribute 'created_ids'\n\ntests\\test_api_users.py:42: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_users.TestPostsAPI object at 0x000001D2FFE01910>, data = {'action': 'update', 'body': 'new', 'expected': False, 'id': 9999.0, ...}\n\n    @allure.description(\"Updates user details by user ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update\", parametrize=True))\n    def test_update_post(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            post_id = extract_post_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid id from Excel: '{data.get('post_id')}'\")\nE           Failed: [ERROR] Invalid id from Excel: 'None'\n\ntests\\test_api_users.py:44: Failed"}, "description": "Updates user details by user ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "5f61f4e7-bd8d-4cd3-9ce2-3dad53d46e5e-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "69a8c2bc-311e-4cc8-969f-11e5c2d9730d-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "d811b081-4c73-4ec3-8a33-027e3e0c5caa-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update', 'id': 9999.0, 'body': 'new', 'id': 'new', 'title': 1.0, 'expected': False, 'note': 'NoValid - Post not found'}"}], "start": 1753213520821, "stop": 1753213520822, "uuid": "d31dc492-372d-4de9-ac86-08a19e5f0928", "historyId": "6182ebfc0250cdb8669819fe89c3b6ce", "testCaseId": "16130e9d55726e09524cf02a0fdf9edc", "fullName": "tests.test_api_users.TestPostsAPI#test_update_post", "labels": [{"name": "epic", "value": "posts API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "subSuite", "value": "TestPostsAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "33216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_users"}]}